<a href="https://colab.research.google.com/github/nayan911/securehack/blob/main/random_forest_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Random Forest Classification

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

C:\Users\ajitg\miniconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\ajitg\miniconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\ajitg\miniconda3\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


## Importing the dataset

In [27]:
data = pd.read_csv('Website Phishing.csv')


In [28]:
data.shape

(1353, 10)

In [29]:
data.head()

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  web_traffic  \
0    1           -1               1           -1             -1            1   
1   -1           -1              -1           -1             -1            0   
2    1           -1               0            0             -1            0   
3    1            0               1           -1             -1            0   
4   -1           -1               1           -1              0            0   

   URL_Length  age_of_domain  having_IP_Address  Result  
0           1              1                  0       0  
1           1              1                  1       1  
2          -1              1                  0       1  
3           1              1                  0       0  
4          -1              1                  0       1

In [30]:
X = data.iloc[:,:-1].values
Y = data.iloc[:,-1].values

In [31]:
X

array([[ 1, -1,  1, ...,  1,  1,  0],
       [-1, -1, -1, ...,  1,  1,  1],
       [ 1, -1,  0, ..., -1,  1,  0],
       ...,
       [-1,  0, -1, ..., -1, -1,  0],
       [ 0,  0,  1, ..., -1,  1,  0],
       [ 1,  0,  1, ..., -1, -1,  0]], dtype=int64)

In [32]:
Y

array([ 0,  1,  1, ...,  1,  1, -1], dtype=int64)

In [33]:
Y.shape

(1353,)

## Splitting the dataset into the Training set and Test set

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [35]:
print(X_train)

[[ 1  0  1 ... -1  1  0]
 [-1 -1 -1 ...  1  1  0]
 [ 1 -1  0 ... -1 -1  0]
 ...
 [ 1  0  1 ...  0  1  0]
 [ 1  0  1 ...  0  1  0]
 [-1  0  0 ... -1  1  0]]


In [36]:
print(y_train)

[-1  1 -1 ... -1 -1  1]


In [37]:
print(X_test)

[[-1  0  1 ...  0  1  0]
 [ 0  0  0 ...  0  1  0]
 [ 1  0  1 ...  0  1  0]
 ...
 [ 1  0 -1 ...  1  1  0]
 [ 1  0 -1 ...  0 -1  0]
 [ 1  0 -1 ... -1 -1  0]]


In [38]:
print(y_test)

[ 1  0 -1  1  1 -1  1  1 -1 -1 -1 -1 -1 -1  1  1 -1  1  0 -1  1  1 -1  1
 -1  1 -1  1  1  1  0 -1 -1 -1 -1 -1  1  1  0 -1 -1 -1  1 -1 -1  1  1 -1
  1  1 -1 -1  1 -1  1  0 -1 -1  1 -1  1  1  1  1  1 -1 -1  1 -1 -1 -1 -1
  1  1 -1 -1  1  1 -1 -1 -1  1 -1  1  1 -1  0 -1  1 -1 -1  1 -1  1  0  1
 -1 -1 -1 -1 -1 -1 -1  1 -1  1  1  1  1  0  1  1  1  0 -1 -1 -1 -1 -1  1
  1 -1 -1 -1  1 -1  0 -1  1  1  0 -1 -1 -1  1  1 -1  0 -1  1  1  0  1 -1
 -1 -1  1  1  1 -1 -1 -1 -1  1  0  1 -1 -1  1 -1  1  0  1  1  1 -1 -1  1
  1 -1  1 -1  1 -1 -1  1  1 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1  1
  1  0 -1  1 -1  1 -1  1 -1 -1  1  1  1 -1  1  1 -1 -1  1 -1  1  0 -1  0
  1 -1  1 -1 -1  0  1  0 -1 -1 -1  1 -1  1  1  1 -1 -1  1  1  1 -1 -1 -1
 -1 -1  1  0  1  1  1  1 -1 -1  1  1 -1 -1  1  1  1 -1  1 -1 -1 -1 -1 -1
 -1 -1 -1 -1  1 -1 -1 -1 -1  1 -1 -1  1  1 -1 -1  0  1 -1 -1  1  0  0  0
  1 -1  1 -1 -1 -1 -1  1 -1  1  1 -1 -1 -1  1  1 -1  1  1  1  1  0 -1 -1
  1  1  1 -1 -1  1 -1  1 -1  0  0 -1 -1  1 -1  1 -1

## Training the Random Forest Classification model on the Training set

In [39]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Predicting a new result

In [40]:
# print(classifier.predict(sc.transform([[30,87000]])))

## Predicting the Test set results

In [41]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-1  1]
 [ 0  0]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1 -1]
 [ 1  1]
 [ 0  0]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1  0]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 0  0]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1 -1]
 [-1  1]
 [ 1  1]
 [ 1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 0  0]
 [ 1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [-1 -1]
 [ 1  0]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1  1]
 [ 1 -1]
 [ 1  1]
 [-1  0]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 0  0]
 [-1  1]
 

## Making the Confusion Matrix

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[153   0  18]
 [  2  24   2]
 [ 17   3 120]]


0.8761061946902655

In [43]:
import pickle
filename = 'RandomForest_Pickle.pkl'
with open(filename, 'wb') as file:
  pickle.dump(classifier, file)

In [46]:
import joblib
RF = joblib.load('RandomForest_Pickle.pkl')

testy = RF.predict([[1,0,1,1,0,0,0,1,1]])
testy

array([-1], dtype=int64)