<a href="https://colab.research.google.com/github/nayan911/securehack/blob/main/random_forest_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Random Forest Classification

## Importing the libraries

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [9]:
dataset = pd.read_csv('Website_Phishing.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [11]:
print(X_train)

[[ 1  0  1 ... -1  1  0]
 [-1 -1 -1 ...  1  1  0]
 [ 1 -1  0 ... -1 -1  0]
 ...
 [ 1  0  1 ...  0  1  0]
 [ 1  0  1 ...  0  1  0]
 [-1  0  0 ... -1  1  0]]


In [12]:
print(y_train)

[-1  1 -1 ... -1 -1  1]


In [13]:
print(X_test)

[[-1  0  1 ...  0  1  0]
 [ 0  0  0 ...  0  1  0]
 [ 1  0  1 ...  0  1  0]
 ...
 [ 1  0 -1 ...  1  1  0]
 [ 1  0 -1 ...  0 -1  0]
 [ 1  0 -1 ... -1 -1  0]]


In [14]:
print(y_test)

[ 1  0 -1  1  1 -1  1  1 -1 -1 -1 -1 -1 -1  1  1 -1  1  0 -1  1  1 -1  1
 -1  1 -1  1  1  1  0 -1 -1 -1 -1 -1  1  1  0 -1 -1 -1  1 -1 -1  1  1 -1
  1  1 -1 -1  1 -1  1  0 -1 -1  1 -1  1  1  1  1  1 -1 -1  1 -1 -1 -1 -1
  1  1 -1 -1  1  1 -1 -1 -1  1 -1  1  1 -1  0 -1  1 -1 -1  1 -1  1  0  1
 -1 -1 -1 -1 -1 -1 -1  1 -1  1  1  1  1  0  1  1  1  0 -1 -1 -1 -1 -1  1
  1 -1 -1 -1  1 -1  0 -1  1  1  0 -1 -1 -1  1  1 -1  0 -1  1  1  0  1 -1
 -1 -1  1  1  1 -1 -1 -1 -1  1  0  1 -1 -1  1 -1  1  0  1  1  1 -1 -1  1
  1 -1  1 -1  1 -1 -1  1  1 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1  1
  1  0 -1  1 -1  1 -1  1 -1 -1  1  1  1 -1  1  1 -1 -1  1 -1  1  0 -1  0
  1 -1  1 -1 -1  0  1  0 -1 -1 -1  1 -1  1  1  1 -1 -1  1  1  1 -1 -1 -1
 -1 -1  1  0  1  1  1  1 -1 -1  1  1 -1 -1  1  1  1 -1  1 -1 -1 -1 -1 -1
 -1 -1 -1 -1  1 -1 -1 -1 -1  1 -1 -1  1  1 -1 -1  0  1 -1 -1  1  0  0  0
  1 -1  1 -1 -1 -1 -1  1 -1  1  1 -1 -1 -1  1  1 -1  1  1  1  1  0 -1 -1
  1  1  1 -1 -1  1 -1  1 -1  0  0 -1 -1  1 -1  1 -1

## Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
print(X_train)

[[ 0.82064819  0.36653081  0.8007526  ... -1.26670829  0.82558588
  -0.36982604]
 [-1.37496465 -1.10248991 -1.63391948 ...  1.3439466   0.82558588
  -0.36982604]
 [ 0.82064819 -1.10248991 -0.41658344 ... -1.26670829 -1.21126103
  -0.36982604]
 ...
 [ 0.82064819  0.36653081  0.8007526  ...  0.03861916  0.82558588
  -0.36982604]
 [ 0.82064819  0.36653081  0.8007526  ...  0.03861916  0.82558588
  -0.36982604]
 [-1.37496465  0.36653081 -0.41658344 ... -1.26670829  0.82558588
  -0.36982604]]


In [17]:
print(X_test)

[[-1.37496465  0.36653081  0.8007526  ...  0.03861916  0.82558588
  -0.36982604]
 [-0.27715823  0.36653081 -0.41658344 ...  0.03861916  0.82558588
  -0.36982604]
 [ 0.82064819  0.36653081  0.8007526  ...  0.03861916  0.82558588
  -0.36982604]
 ...
 [ 0.82064819  0.36653081 -1.63391948 ...  1.3439466   0.82558588
  -0.36982604]
 [ 0.82064819  0.36653081 -1.63391948 ...  0.03861916 -1.21126103
  -0.36982604]
 [ 0.82064819  0.36653081 -1.63391948 ... -1.26670829 -1.21126103
  -0.36982604]]


## Training the Random Forest Classification model on the Training set

In [18]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Predicting a new result

In [ ]:
# print(classifier.predict(sc.transform([[30,87000]])))

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[153   0  18]
 [  2  24   2]
 [ 17   3 120]]


0.8761061946902655

In [25]:
import pickle
filename = 'RandomForest_Pickle.pkl'
with open(filename, 'wb') as file:
  pickle.dump(classifier, file)